apiVersion: monitoring.operator.ibm.com/v1alpha1
kind: PrometheusExt
metadata:
  name: ibm-monitoring
spec:
    storageClassName: rook-ceph-block-internal
    clusterAddress: "icp-console.apps.dybo-ocp4.os.fyre.ibm.com"
    clusterPort: 8443
    grafanaSvcName: "ibm-monitoring-grafana"
    grafanaSvcPort: 8090
    imagePullSecrets:
    - infra-registry-key
    routerImage: hyc-cloud-private-release-docker-local.artifactory.swg-devops.com/ibmcom-amd64/icp-management-ingress:2.5.0
    prometheusConfig:
      serviceAccount: default
      imageRepo: hyc-cloud-private-release-docker-local.artifactory.swg-devops.com/ibmcom-amd64/prometheus
      imageTag: v2.8.0-build.1
      retention: 24h
      servicePort: 9090
      nodeMemoryThreshold: 8
      nodeCPUThreshold: 85
      logLevel: debug
    alertManagerConfig:
      serviceAccount: default
      imageRepo: hyc-cloud-private-release-docker-local.artifactory.swg-devops.com/ibmcom-amd64/alertmanager
      imageTag: v0.15.0-build.1
      servicePort: 9093
      logLevel: debug
    certs:
      caSecret: cluster-ca-cert
      provider: certmanager
      monitoringSecret: ibm-monitoring-certs
      monitoringClientSecret: ibm-monitoring-client-certs
      issuer: icp-ca-issuer 
    iamProvider:
      namespace: kube-system
      idProviderSvc: platform-identity-provider
      idProviderSvcPort: 4300
      idManagementSvc: platform-identity-management
      idManagementSvcPort: 4500

        
