apiVersion: monitoring.operator.ibm.com/v1alpha1
kind: PrometheusExt
metadata:
  name: ibm-monitoring
spec:
    storageClassName: rook-ceph-block-internal
    clusterAddress: "icp-console.apps.dybo-ocp4.os.fyre.ibm.com"
    clusterPort: 8443
    grafanaSvcName: "ibm-monitoring-grafana"
    grafanaSvcPort: 8090
    imagePullSecrets:
    - infra-registry-key
    routerImage: hyc-cloud-private-edge-docker-local.artifactory.swg-devops.com/ibmcom-amd64/icp-management-ingress:2.5.0
    prometheusConfig:
      serviceAccount: ibm-monitoring-prometheusext-operand
      imageRepo: hyc-cloud-private-edge-docker-local.artifactory.swg-devops.com/ibmcom-amd64/prometheus
      imageTag: v2.15.2-build.1
      retention: 24h
      servicePort: 9090
      nodeMemoryThreshold: 8
      nodeCPUThreshold: 85
      logLevel: debug
    alertManagerConfig:
      serviceAccount: ibm-monitoring-prometheusext-operand
      imageRepo: hyc-cloud-private-edge-docker-local.artifactory.swg-devops.com/ibmcom-amd64/alertmanager
      imageTag: v0.20.0-build.1
      servicePort: 9093
      logLevel: debug
    mcmMonitor:
      isHubCluster: false
      image: hyc-cloud-private-edge-docker-local.artifactory.swg-devops.com/ibmcom-amd64/prometheus-controller:v1.1.0-build.2
      helpeImage: hyc-cloud-private-edge-docker-local.artifactory.swg-devops.com/ibmcom-amd64/icp-initcontainer:1.0.0-build.2
      serviceAccount: ibm-monitoring-mcm-ctl
    certs:
      monitoringSecret: ibm-monitoring-certs
      monitoringClientSecret: ibm-monitoring-client-certs
      issuer: cs-ca-issuer 
    iamProvider:
      idProviderSvc: platform-identity-provider
      idProviderSvcPort: 4300
      idManagementSvc: platform-identity-management
      idManagementSvcPort: 4500

        
