apiVersion: apps/v1
kind: Deployment
metadata:
  name: ibm-monitoring-prometheus-operator-ext
spec:
  replicas: 1
  selector:
    matchLabels:
      name: ibm-monitoring-prometheus-operator-ext
  template:
    metadata:
      labels:
        name: ibm-monitoring-prometheus-operator-ext
    spec:
      serviceAccountName: ibm-monitoring-prometheus-operator-ext
      containers:
        - name: ibm-monitoring-prometheus-operator-ext
          # Replace this with the built image name
          image: REPLACE_IMAGE
          command:
          - ibm-monitoring-prometheus-operator-ext
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "ibm-monitoring-prometheus-operator-ext"
