apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: ibm-monitoring
    app.kubernetes.io/instance: prometheusext
    app.kubernetes.io/managed-by: ibm-monitoring-prometheusext-operator
  name: ibm-monitoring-prometheus-operator-ext
spec:
  replicas: 1
  selector:
    matchLabels:
      name: ibm-monitoring-prometheus-operator-ext
  template:
    metadata:
      labels:
        app.kubernetes.io/name: ibm-monitoring
        app.kubernetes.io/instance: prometheusext
        app.kubernetes.io/managed-by: ibm-monitoring-prometheusext-operator
        name: ibm-monitoring-prometheus-operator-ext
      annotations:
        productName: IBM Cloud Platform Common Services
        productID: "068a62892a1e4db39641342e592daa25"
        productVersion: "3.4.0"
        productMetric: FREE
    spec:
      serviceAccountName: ibm-monitoring-prometheus-operator-ext
      hostIPC: false
      hostNetwork: false
      hostPID: false
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: beta.kubernetes.io/arch
                operator: In
                values:
                - amd64
                - ppc64le
                - s390x
      containers:
        - name: ibm-monitoring-prometheus-operator-ext
          image: quay.io/opencloudio/ibm-monitoring-prometheusext-operator:1.8.0
          command:
          - ibm-monitoring-prometheusext-operator
          imagePullPolicy: Always
          securityContext:
            privileged: false
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            capabilities:
              drop:
              - ALL
          resources:
            limits:
              cpu: 50m
              memory: 128Mi
            requests:
              cpu: 20m
              memory: 64Mi
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "ibm-monitoring-prometheusext-operator"
            - name: AM_IMAGE
              value: quay.io/opencloudio/alertmanager@sha256:9b084bb932cadafbb085fa9236c7cc9cfab29740a09f63c9b77e1c722b041826
            - name: PROME_IMAGE
              value: quay.io/opencloudio/prometheus@sha256:efd42bc1d24b298c11234ad42d89bf3f76889e184f65d392dddbcd5051ed36d8
            - name: CM_RELOAD_IMAGE
              value: quay.io/opencloudio/configmap-reload@sha256:02233bcce274ca6fcdba80fe31b559caac3cfabdf6d63580eaf498533f2cf80b
            - name: PROM_OP_IMAGE
              value: quay.io/opencloudio/prometheus-operator@sha256:ee2e9f5d6d06603e159a22ccfed8d9572828859559758fbcb2604a5e5c8d1f27
            - name: PROM_CONF_IMAGE
              value: quay.io/opencloudio/prometheus-config-reloader@sha256:bdfd86417fd21276b8bc4abdc2ea2d1bc8f1b6297c2af6b2c4842d72b683b327
            - name: ROUTER_IMAGE
              value: quay.io/opencloudio/icp-management-ingress@sha256:c49e551f9f68f2e024a8a50e35f2ce4a6ec86f169d9bfb489b47fa6e8e216571
            - name: MCM_HELPER_IMAGE
              value: quay.io/opencloudio/icp-initcontainer@sha256:9aad9fd724ec9308bec711d7738b5f0ae0c37a72ffb19a26dbcf622f1a603e89
            - name: MCM_IMAGE
              value: quay.io/opencloudio/prometheus-controller@sha256:b1d407b340663762506b699fae982d36ed70dc7a64c24613d898fefb690f8c75
