apiVersion: apps/v1
kind: Deployment
metadata:
  name: ibm-monitoring-prometheus-operator-ext
  
spec:
  replicas: 1
  selector:
    matchLabels:
      name: ibm-monitoring-prometheus-operator-ext
  template:
    metadata:
      labels:
        name: ibm-monitoring-prometheus-operator-ext
      annotations:
        productName: IBM Cloud Platform Common Services
        productID: "068a62892a1e4db39641342e592daa25"
        productVersion: "3.3.0"
        productMetric: FREE
    spec:
      serviceAccountName: ibm-monitoring-prometheus-operator-ext
      containers:
        - name: ibm-monitoring-prometheus-operator-ext
          image: quay.io/opencloudio/ibm-monitoring-prometheusext-operator
          command:
          - ibm-monitoring-prometheusext-operator
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "ibm-monitoring-prometheusext-operator"
